# Generated by Django 4.2.4 on 2023-08-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads_app', '0002_rename_name_ad_ad_name_rename_name_location_loc_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLocationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('visitor_count', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ads_app.location')),
            ],
        ),
    ]
