# Generated by Django 4.2.4 on 2023-08-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads_app', '0003_dailylocationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='ad_pictures'),
        ),
    ]
